### ISSUE TITLE
Library includes play-services v6.5.87

### ISSUE THREAD

**Issue by juanto121** [bertrandmartel/iotf-android#1]
The dependency : 
 `compile 'com.google.android.gms:play-services:6.5.87'`

causes gradle error:

>  more than one library with package name 'com.google.android.gms:play-services' 

 when including a more recent version of the play-services library. A simple fix is  to include the iotf-android excluding the library and making sure another version of play-services library is added to the application.

```
compile ('akinaru:iotf-android:0.2'){
   exclude group: 'com.google.android.gms'
}
```

Is it safe to do so? I haven't looked at what might happen when using another version of play-services.

**Comment by bertrandmartel** [comment]
Hello, thank you for pointing this out. `com.google.android.gms` is used to call `ProviderInstaller.installIfNeeded(mContext)` which will automatically update the Security Provider if  a higher version/patch exists : http://developer.android.com/training/articles/security-gms-provider.html.

This check occurs before a connection between client & server is created. If you don't need `com.google.android.gms:play-services` in your project, I would say it is not necessary to replace this dependency because the Security Provider will be updated. If you are using `com.google.android.gms:play-services` in your project and requiring some features of it, then you have to exclude the group or module like you did. 

Even if you put a higher or lower version of google play, it will always update with the last security patches
